// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: update_player.proto

/*
	Package netmsg is a generated protocol buffer package.

	It is generated from these files:
		update_player.proto

	It has these top-level messages:
		UpdatePlayer
*/
package netmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdatePlayer struct {
	ClientSlot        int32   `protobuf:"varint,1,opt,name=ClientSlot,proto3" json:"ClientSlot,omitempty"`
	X                 float64 `protobuf:"fixed64,2,opt,name=X,proto3" json:"X,omitempty"`
	Y                 float64 `protobuf:"fixed64,3,opt,name=Y,proto3" json:"Y,omitempty"`
	IsKeyLeftPressed  bool    `protobuf:"varint,4,opt,name=IsKeyLeftPressed,proto3" json:"IsKeyLeftPressed,omitempty"`
	IsKeyRightPressed bool    `protobuf:"varint,5,opt,name=IsKeyRightPressed,proto3" json:"IsKeyRightPressed,omitempty"`
}

func (m *UpdatePlayer) Reset()                    { *m = UpdatePlayer{} }
func (m *UpdatePlayer) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlayer) ProtoMessage()               {}
func (*UpdatePlayer) Descriptor() ([]byte, []int) { return fileDescriptorUpdatePlayer, []int{0} }

func (m *UpdatePlayer) GetClientSlot() int32 {
	if m != nil {
		return m.ClientSlot
	}
	return 0
}

func (m *UpdatePlayer) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *UpdatePlayer) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *UpdatePlayer) GetIsKeyLeftPressed() bool {
	if m != nil {
		return m.IsKeyLeftPressed
	}
	return false
}

func (m *UpdatePlayer) GetIsKeyRightPressed() bool {
	if m != nil {
		return m.IsKeyRightPressed
	}
	return false
}

func init() {
	proto.RegisterType((*UpdatePlayer)(nil), "netmsg.UpdatePlayer")
}
func (m *UpdatePlayer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdatePlayer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClientSlot != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintUpdatePlayer(dAtA, i, uint64(m.ClientSlot))
	}
	if m.X != 0 {
		dAtA[i] = 0x11
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.X))))
		i += 8
	}
	if m.Y != 0 {
		dAtA[i] = 0x19
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Y))))
		i += 8
	}
	if m.IsKeyLeftPressed {
		dAtA[i] = 0x20
		i++
		if m.IsKeyLeftPressed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.IsKeyRightPressed {
		dAtA[i] = 0x28
		i++
		if m.IsKeyRightPressed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeVarintUpdatePlayer(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UpdatePlayer) Size() (n int) {
	var l int
	_ = l
	if m.ClientSlot != 0 {
		n += 1 + sovUpdatePlayer(uint64(m.ClientSlot))
	}
	if m.X != 0 {
		n += 9
	}
	if m.Y != 0 {
		n += 9
	}
	if m.IsKeyLeftPressed {
		n += 2
	}
	if m.IsKeyRightPressed {
		n += 2
	}
	return n
}

func sovUpdatePlayer(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozUpdatePlayer(x uint64) (n int) {
	return sovUpdatePlayer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UpdatePlayer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpdatePlayer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdatePlayer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdatePlayer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSlot", wireType)
			}
			m.ClientSlot = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpdatePlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientSlot |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.X = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Y = float64(math.Float64frombits(v))
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsKeyLeftPressed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpdatePlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsKeyLeftPressed = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsKeyRightPressed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpdatePlayer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsKeyRightPressed = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipUpdatePlayer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthUpdatePlayer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUpdatePlayer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUpdatePlayer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUpdatePlayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUpdatePlayer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthUpdatePlayer
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowUpdatePlayer
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipUpdatePlayer(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthUpdatePlayer = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUpdatePlayer   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("update_player.proto", fileDescriptorUpdatePlayer) }

var fileDescriptorUpdatePlayer = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x48, 0x49,
	0x2c, 0x49, 0x8d, 0x2f, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0xcb, 0x4b, 0x2d, 0xc9, 0x2d, 0x4e, 0x57, 0x5a, 0xc2, 0xc8, 0xc5, 0x13, 0x0a, 0x96, 0x0f,
	0x00, 0x4b, 0x0b, 0xc9, 0x71, 0x71, 0x39, 0xe7, 0x64, 0xa6, 0xe6, 0x95, 0x04, 0xe7, 0xe4, 0x97,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x89, 0x08, 0xf1, 0x70, 0x31, 0x46, 0x48, 0x30,
	0x29, 0x30, 0x6a, 0x30, 0x06, 0x31, 0x46, 0x80, 0x78, 0x91, 0x12, 0xcc, 0x10, 0x5e, 0xa4, 0x90,
	0x16, 0x97, 0x80, 0x67, 0xb1, 0x77, 0x6a, 0xa5, 0x4f, 0x6a, 0x5a, 0x49, 0x40, 0x51, 0x6a, 0x71,
	0x71, 0x6a, 0x8a, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x86, 0xb8, 0x90, 0x0e, 0x97, 0x20,
	0x58, 0x2c, 0x28, 0x33, 0x3d, 0x03, 0xae, 0x98, 0x15, 0xac, 0x18, 0x53, 0xc2, 0x49, 0xe0, 0xc4,
	0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf1, 0x58, 0x8e, 0x21,
	0x89, 0x0d, 0xec, 0x0f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x88, 0x27, 0xa6, 0xde,
	0x00, 0x00, 0x00,
}
